### Basic Math

In [1]:
import numpy as np

$log_b(a) = c \Leftrightarrow  b^c = a $

In [20]:
a = 400
c = np.log2(a) 
assert 2**c - a < 0.00001

Change of base

${\displaystyle \log _{b}x={\frac {\log _{k}x}{\log _{k}b}}.\,}$

In [24]:
assert np.log2(10) - np.log10(10)/np.log10(2) < 0.001

$log \frac{p(x}{q(x)}  \Leftrightarrow　p(x) - q(x)$

In [6]:
np.log(2/4) == np.log(2) - np.log(4)

True

### Calculus

Function \
$x \in X f(x) = y \in Y$ \
$x \in \mathbb{R} f y = f(x) \in \mathbb{R}$

Property \
$f(\alpha x) = \alpha f(x)$ \
$f(x_1 + x_2) = f(x_1) + f(x_2)$

$f(x) = ax $ linear \
$f(x) = ax + b $ affine 

Nonlinear functions: all others 
- power function: $f(x) = cx^a$ \
a = 2 square \
a 1/2 = square root \
$-1$ = inverse

- exponential functions: $f(x) = ca^x$ for some a $\in \mathbb{r}$
a = e 2.7

- logarithm functions: $y=a^x x$ \
$y=a^x$ \
$x = log_a y$

Derivative \
if I slightly move x, how does f(x) change \
limit of rate of variation of function = derivative =  slope of tangent\
tangent is flat = no variation from small perturbation of f(x)

$(cf(x))' = cf'(x) $ \
$(f(x)+g(x))' = f'(x) + g'(x)$

$(\frac{u}{v})' = \frac{u'v - uv'}{v^2}$ \
$\frac{u}{v} = u \times \frac{1}{v} = u' \times \frac{1}{v} + u \times (\frac{1}{v})' $

$f(x) = (2x)^3 = u^3$ with $u = 2x \rightarrow 3(2x)^2 * 2$ \
$f(x) = 8 x^3 \rightarrow f'(x) = 8 \times 3x^2 = 24x^2$

Polynomial function, derivative gives one degree lower polynomial

![](https://demonstrations.wolfram.com/AFifthDegreePolynomialAndItsDerivatives/img/popup_3.png)

Approximation

Taylor function

Mean Value theorem

$f'(c) = \frac{f(b) - f(a)}{b - a}$
$f(a) = f(b) \Rightarrow$  $\exists$ c s.t. $f'(c) = 0$
$\int_a^bf(t)dt = f(c) \times (b -a )$ where $f(c) = $ mean value

Integration by part $\Leftarrow$ (uv)' = u'v + uv'

$\int u'(x) \times v(x) dx = - \int u(x) v'(x) + u(x)v(x)$

$\int ln x dx = x ln x - x + C$

Substitution rule
$\int f'(u) \times u' = f(u)(+C)$ \
$(f(u))' = f'(u) \times u'$ \
$\int f(u) \times u' = F(u)$ \
$(F(u))' = F'(u) \times u' = f(u) \times u'$
$\int cos(e^x) \times e^x dx = sin(e^x) + C$

### Linear Algebra

In [3]:
import numpy as np
from numpy import random
x = np.arange(1, 4)
y = np.arange(6, 9)
A = np.arange(1, 10).reshape(3, 3)
B = random.randint(1, 10, (3, 3))

print("x: ", x)
print("y: ", y)
print("A: ", A)
print("B: ", B)

x:  [1 2 3]
y:  [6 7 8]
A:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
B:  [[4 2 3]
 [5 6 9]
 [6 4 3]]


In [8]:
#"Inner product of x and y"
print(np.dot(x, y))
print(np.matmul(x, y))
print(x@y)

#outer product
np.outer(x, y)

#"Matrix Multiplication of A and B"
print(np.dot(A, B))
print(np.matmul(A, B))
print(A@B)

44
44
44
[[ 32  26  30]
 [ 77  62  75]
 [122  98 120]]
[[ 32  26  30]
 [ 77  62  75]
 [122  98 120]]
[[ 32  26  30]
 [ 77  62  75]
 [122  98 120]]
