In [1]:
import tensorflow as tf
import timeit

In [2]:
start = timeit.timeit()

def eager_function(x):
    result = x**2
    print(result)
    return result

x = tf.constant([1, 2, 3, 4, 5])

eager_function(x)
end = timeit.timeit()

print(end - start)

tf.Tensor([ 1  4  9 16 25], shape=(5,), dtype=int32)
-0.0007940000000004055


In [3]:
start = timeit.timeit()

def eager_function(x):
    result = x**2
    print(result)
    return result

x = tf.constant([1, 2, 3, 4, 5])

eager_function(x)
graph_function = tf.function(eager_function)
graph_function(x)
end = timeit.timeit()

print(end - start)

tf.Tensor([ 1  4  9 16 25], shape=(5,), dtype=int32)
Tensor("pow:0", shape=(5,), dtype=int32)
0.00017729999999982482


Not much difference for the small computation

In [5]:
print("Eager time:", timeit.timeit(lambda: eager_function(x), number=1))
print("Graph time:", timeit.timeit(lambda: graph_function(x), number=1))

tf.Tensor([ 1  4  9 16 25], shape=(5,), dtype=int32)
Eager time: 0.0003361999999995646
Graph time: 0.0004989000000001909


In [6]:
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Flatten, Dense

inputs=Input(shape=(28, 28))
x = Flatten()(inputs)
x = Dense(256, "relu")(x)
x = Dense(256, "relu")(x)
x = Dense(256, "relu")(x)
outputs = Dense(10, "softmax")(x)

input_data = tf.random.uniform([100, 28, 28])

Huge difference for more computationally heave one

In [15]:
eager_model = Model(inputs, outputs)
print("Eager time:", timeit.timeit(lambda: eager_model(input_data),number=10000))
graph_model = tf.function(eager_model)
print("Graph time:", timeit.timeit(lambda: graph_model(input_data),number=10000))

Eager time: 10.104331000000002
Graph time: 4.529903300000001
